/// Flutter icons InvoiceIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InvoiceIcon
///      fonts:
///       - asset: fonts/InvoiceIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class InvoiceIcon {
  InvoiceIcon._();

  static const _kFontFam = 'InvoiceIcon';
  static const String? _kFontPkg = null;

  static const IconData nlxyri01 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
