import 'package:flutter/services.dart';

Map<String, LogicalKeyboardKey> KeyBoardKeys = {
  'a': LogicalKeyboardKey.keyA,
  's': LogicalKeyboardKey.keyS,
  'd': LogicalKeyboardKey.keyD,
  'f': LogicalKeyboardKey.keyF,
  'g': LogicalKeyboardKey.keyG,
  'h': LogicalKeyboardKey.keyH,
  'j': LogicalKeyboardKey.keyJ,
  'k': LogicalKeyboardKey.keyK,
  'l': LogicalKeyboardKey.keyL,
  'z': LogicalKeyboardKey.keyZ,
  'x': LogicalKeyboardKey.keyX,
  'c': LogicalKeyboardKey.keyC,
  'v': LogicalKeyboardKey.keyV,
  'b': LogicalKeyboardKey.keyB,
  'n': LogicalKeyboardKey.keyN,
  'm': LogicalKeyboardKey.keyM,
  'q': LogicalKeyboardKey.keyQ,
  'w': LogicalKeyboardKey.keyW,
  'e': LogicalKeyboardKey.keyE,
  'r': LogicalKeyboardKey.keyR,
  't': LogicalKeyboardKey.keyT,
  'y': LogicalKeyboardKey.keyY,
  'u': LogicalKeyboardKey.keyU,
  'i': LogicalKeyboardKey.keyI,
  'o': LogicalKeyboardKey.keyO,
  'p': LogicalKeyboardKey.keyP,
  'f2': LogicalKeyboardKey.f2,
  'f3': LogicalKeyboardKey.f3,
  'f4': LogicalKeyboardKey.f4,
  'f5': LogicalKeyboardKey.f5,
  'f6': LogicalKeyboardKey.f6,
  'f7': LogicalKeyboardKey.f7,
  'f8': LogicalKeyboardKey.f8,
  'f9': LogicalKeyboardKey.f9,
  'f10': LogicalKeyboardKey.f10,
  'f11': LogicalKeyboardKey.f11,
  'f12': LogicalKeyboardKey.f12,
};

List keyBoardList = [
  'f2',
  'f3',
  'f4',
  'f5',
  'f6',
  'f7',
  'f8',
  'f9',
  'f10',
  'f11',
  'f12',
  'a',
  's',
  'd',
  'f',
  'g',
  'h',
  'j',
  'k',
  'l',
  'z',
  'x',
  'c',
  'v',
  'b',
  'n',
  'm',
  'q',
  'w',
  'e',
  'r',
  't',
  'y',
  'u',
  'i',
  'o',
  'p',
];